name: carbonplan
channels:
  - conda-forge
dependencies:
  - pangeo-notebook=2021.06.05
  - awswrangler
  - boto3
  - bottleneck
  - cartopy
  - code-server
  - cython
  - fastparquet
  - gcsfs
  - gdal
  - geopandas
  - h5py
  - h5netcdf
  - intake
  - intake-geopandas
  - intake-parquet
  - intake-xarray
  - ipykernel
  - ipython
  - ipytree
  - ipywidgets
  - jedi
  - jupyterlab
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  - libgdal
  - matplotlib
  - nb_conda_kernels
  - nodejs
  - numba
  - numcodecs
  - numpy
  - oauth2client
  - pandas
  - pre_commit
  - pykdtree
  - pygeos
  - pygraphviz
  - pyproj
  - pytest
  - python-graphviz
  - python-wget
  - rasterio
  - regionmask
  - rio-cogeo
  - rioxarray
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - tenacity
  - tqdm
  - utm
  - watermark
  - xarray
  - xgboost
  - zarr
  - pip
  - pip:
      - carbonplan
      - carbonplan-data
      - carbonplan-styles
      - git+https://github.com/carbonplan/trace.git@main
      - git+https://github.com/pangeo-data/xbatcher@f9d40fdb0936c2d97b1964f2ce2ae4481ee1f715
