name: carbonplan
channels:
  - conda-forge
dependencies:
  - pangeo-notebook=2021.05.15
  - boto3
  - bottleneck
  - cartopy
  - code-server
  - cython
  - fastparquet
  - gcsfs
  - gdal
  - geopandas
  - h5py
  - h5netcdf
  - intake
  - intake-geopandas
  - intake-parquet
  - intake-stac
  - intake-xarray
  - ipykernel
  - ipython
  - ipyleaflet
  - ipytree
  - ipywidgets
  - jedi
  - jupyterlab
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  - libgdal
  - matplotlib
  - nb_conda_kernels
  - netcdf4
  - nodejs
  - numba
  - numcodecs
  - numpy
  - oauth2client
  - openpyxl
  - pandas
  - pre_commit
  - prefect
  - pykdtree
  - pygeos
  - pygraphviz
  - pyproj
  - pyresample
  - pystac
  - pystan
  - pytest
  - python-graphviz
  - python-wget
  - rasterio
  - regionmask
  - rio-cogeo
  - rioxarray
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - xarray
  - xgboost
  - xlrd
  - yarn
  - zarr
  - pip
  - pip:
      - carbonplan
      - carbonplan-data
      - carbonplan-styles
      - rio-tiler-mvt
      - git+https://github.com/carbonplan/trace.git@main
